import type { Report } from "./types";

/** Static sample report — $0 API cost, used by /sample-report/[slug]. */
export const SAMPLE_REPORT: Report = {
  report_id: "sample-123-main-st-austin-tx-78704",
  generated_at: "2026-07-01T12:00:00Z",
  intent: "investor",
  disclaimer:
    "HouseFax is a decision-support tool, not financial, legal, or real-estate advice. AVM estimates are models, not appraisals.",
  property_facts: {
    address: "123 Main St, Austin, TX 78704",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_footage: 1680,
    lot_size: 6500,
    year_built: 1988,
    last_sale_date: "2019-06-15",
    last_sale_price: 385000,
    annual_taxes: 7200,
    source_ids: ["rentcast:property"],
  },
  executive_verdict: {
    verdict: "Cautious Buy",
    confidence: "medium",
    summary:
      "Solid rental fundamentals with a mid-5% cap rate under standard assumptions [rentcast:avm-rent], but the AVM range is wide enough that overpaying is a real risk [rentcast:avm-value]. Best suited to a patient investor who underwrites conservatively.",
    best_fit_buyer: "Buy-and-hold investor targeting cash flow in South Austin",
    worst_fit_buyer: "Primary-residence buyer needing a turnkey, low-maintenance home",
  },
  payment_model: {
    purchase_price: 450000,
    down_payment: 90000,
    down_payment_pct: 0.2,
    loan_amount: 360000,
    annual_rate: 0.0685,
    rate_source_id: "fred:MORTGAGE30US",
    term_years: 30,
    monthly_principal_interest: 2348.12,
    monthly_taxes: 600,
    monthly_insurance: 187.5,
    all_in_monthly: 3135.62,
  },
  investment_model: {
    monthly_rent_estimate: 2650,
    rent_range_low: 2450,
    rent_range_high: 2850,
    vacancy_rate: 0.05,
    gross_annual_income: 30195,
    operating_expenses_annual: 14200,
    noi_annual: 15995,
    cap_rate: 0.0355,
    monthly_cash_flow: -802.12,
    cash_invested: 90000,
    cash_on_cash_return: -0.107,
    source_ids: ["rentcast:avm-rent", "tool:cash-flow"],
  },
  comp_analysis: {
    comps: [
      {
        address: "118 Oak Ave, Austin, TX 78704",
        distance_miles: 0.4,
        sale_price: 439000,
        sale_date: "2025-11-02",
        bedrooms: 3,
        bathrooms: 2,
        square_footage: 1620,
        price_per_sqft: 271,
      },
      {
        address: "210 Cedar Ln, Austin, TX 78704",
        distance_miles: 0.7,
        sale_price: 465000,
        sale_date: "2025-09-18",
        bedrooms: 3,
        bathrooms: 2.5,
        square_footage: 1750,
        price_per_sqft: 266,
      },
      {
        address: "55 Elm Ct, Austin, TX 78704",
        distance_miles: 0.9,
        sale_price: 428000,
        sale_date: "2025-08-01",
        bedrooms: 3,
        bathrooms: 2,
        square_footage: 1580,
        price_per_sqft: 271,
      },
    ],
    subject_price_per_sqft: 268,
    median_comp_price_per_sqft: 271,
    pricing_delta_pct: -0.011,
    narrative:
      "Subject prices roughly in line with nearby 3/2 sales from the last 12 months [rentcast:comps]. No clear under/overpriced signal at the asking AVM.",
    source_ids: ["rentcast:comps"],
  },
  neighborhood: {
    median_household_income: 78500,
    population: 4200,
    narrative:
      "Tract-level ACS data shows stable median household income and modest population growth [census:acs5]. This section uses objective Census criteria only — no demographic steering.",
    source_ids: ["census:acs5"],
  },
  risk_flags: [
    {
      category: "flood",
      severity: "low",
      detail: "FEMA NFHL returns Zone X (minimal flood hazard) at the parcel centroid [fema:nfhl].",
      source_ids: ["fema:nfhl"],
    },
    {
      category: "maintenance",
      severity: "moderate",
      detail: "1988 build year implies aging systems (roof, HVAC, plumbing) within a typical 10–15 year replacement window.",
      source_ids: ["rentcast:property"],
    },
  ],
  questions_to_ask: [
    "When was the roof last replaced, and is there remaining warranty?",
    "What is the current property tax assessment trajectory after a purchase reset?",
    "Are there any HOA or municipal special assessments pending?",
    "Has the foundation been inspected in the last 5 years?",
  ],
  sources: [
    { id: "rentcast:property", label: "RentCast property record" },
    { id: "rentcast:avm-value", label: "RentCast AVM value" },
    { id: "rentcast:avm-rent", label: "RentCast long-term rent AVM" },
    { id: "rentcast:comps", label: "RentCast comparable sales" },
    { id: "fred:MORTGAGE30US", label: "FRED 30-year mortgage rate" },
    { id: "census:acs5", label: "Census ACS 5-year tract profile" },
    { id: "fema:nfhl", label: "FEMA National Flood Hazard Layer" },
    { id: "tool:cash-flow", label: "HouseFax cash-flow calculator" },
  ],
  eval_passed: true,
  eval_failures: [],
};
